@plr = player()


@hero = associative_array(
            'name': '§4U§4l§4t§4r§4a§1man',
            'class': 'ultraman',
            'sig': 'pC/rEcT5HuW7a1h41xcLPBJBwBuo1qNethCDcYcaidWjGqYO0A4XbbNIbEOpWolbksEVKqtDFkQU74rFUSrhsjMSr2sIlNgkr6sw2WkG8ohldurZd3t4CfQU/p2j+nbzk3faerToILB0dtMlR8gez2CvRwUsSu3h3N7wrup4DYLEAuQM5p0Vr4Sg3LLp8dckUTu25gHgcu78TPWcHsRVTGs9fD5Iggl5TbbM4PM1DCTZnLCsDwJJtlg9s3sdIUJy7tgTmVk8obj+G/JhQJ6pYmxOpkDLjheZMOmceIe2bupR9jx1TclQ4Gcx5rYhdarTOZkIKOxcU411dQPSNgXUjzkEjp/bxtGxYPV743HXil7hdmNZ1qacQ+rXaR2qefo1qXLB+gxAbabhnS+EJ0Ujxg0Z2ktLo+Vh7l3kYe86u2vREJlfbo+hPPieAVmzdXBsuW/wqWULqCb7itN2djvJ2F6ciTqRPhjVfo7sauM7H6FC0GQMfvJxb5Fft1bbyHfXXEeLsDWptYljCmcl8zIEPFoGENPfmlHizzJMSbZYZkaCXPTqb3FHEOvi75100hkDL9qale0R2SWqnGbLGEoQjMyE2tvd8R9owIdwD987pvWImKQOzKtYiTlC8jJKCH4j+AuXm3Yd422fbkdDqye/pXZVFNvoAYoLHCC0p+YTPuk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0OTUyMzkzMDMsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjZiN2FkYTRlZTRiZDhjZTU4NWRhZTMzZTkxOTI1ZjlkNmRkNGY2OWE1ZjUyNDFkOWI1MTE4NzUzNGU5OCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "This World Belongs To Me!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
